version: "3.7"
services:
  app-nginx:
    build:
      context: app/docker
      dockerfile: dev/nginx/Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8081:80"

  app-php-fpm:
    build:
      context: app/docker
      dockerfile: dev/php-fpm/Dockerfile
    volumes:
      - ./app:/app
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      PHP_IDE_CONFIG: serverName=API
      DB_HOST: app-postgres
      DB_USER: app
      DB_PASSWORD: secret
      DB_NAME: app

  app-php-cli:
    build:
      context: app/docker
      dockerfile: dev/php-cli/Dockerfile
    volumes:
      - ./app:/app
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      DB_HOST: app-postgres
      DB_USER: app
      DB_PASSWORD: secret
      DB_NAME: app

  app-postgres:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    volumes:
      - app-postgres:/var/lib/postgresql/data
    ports:
      - "54321:5432"

volumes:
  app-postgres:
