doctrine:
    dbal:
        server_version: '13.2'
        url: '%env(resolve:DATABASE_URL)%'
        driver: 'pdo_pgsql'
        charset: utf8
        types:
            user_user_id: 'User\Infrastructure\Doctrine\Types\IdType'
            user_user_username: 'User\Infrastructure\Doctrine\Types\UsernameType'
            user_user_status: 'User\Infrastructure\Doctrine\Types\StatusType'
        default_table_options:
            charset: utf8
            collate: ~

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/User/Model'
                prefix: 'User\Model'
                alias: User
